---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: usbtest-delete-self-binding-node
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: usbtest:nodeget
subjects:
- kind: ServiceAccount
  name: usb-watcher
  namespace: usbtest

