---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: usbtest:nodeget
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list    # used to permit label selector in "kubectl get nodes ..." instead of "get node/"

