---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usbtest
  namespace: usb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: usbtest
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: usbtest
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - while true; do date; echo dummy workload; sleep 15; done
        image: docker.io/library/busybox:latest
        imagePullPolicy: IfNotPresent
        name: workload
# e.g. for a ttyUSB device to be passed in
#        volumeMounts:
#        - mountPath: /dev/ttyACM0
#          name: ttyusb

      - env:
        - name: NODEHOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: PODNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: SLEEP
          value: "5"
        - name: NODELABEL
          value: feature.node.kubernetes.io/usb-03_046d_c52b.present
        image: quay.io/dbaker/sidecar-destruct:v0.1
        imagePullPolicy: IfNotPresent
        name: sidecar-destruct
      # NODESELECTOR -- this is a sample USB identifier for Logitech unified
      # receiver; which I happen to have a spare of to test plug/unplug with ease
      nodeSelector:
        feature.node.kubernetes.io/usb-03_046d_c52b.present: "true"
      securityContext:
        runAsNonRoot: true
      serviceAccount: usb-watcher
      serviceAccountName: usb-watcher

# Sample: pass in a hostPath device
#      volumes:
#      - hostPath:
#          path: /dev/ttyUSB-xxxx-xxxx
#          type: CharDevice
#        name: ttyusb

