---
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: delete-self-binding
  namespace: usb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: delete-self
subjects:
- kind: ServiceAccount
  name: usb-watcher
  namespace: usb

